=== fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/fchavonet/web-db_visual_adventure_cards_api/schema/card.schema.json",
  "title": "Visual Adventure Card",
  "type": "object",
  "required": [
    "id",
    "part",
    "number",
    "title_jp",
    "rarity",
    "front_image_url",
    "back_image_url",
    "updated_at"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^p[\\w]+-\\d{3}[a-z]?$"
    },
    "part": {
      "type": "string",
      "minLength": 1
    },
    "number": {
      "type": "string",
      "pattern": "^\\d{3}$"
    },
    "year": {
      "type": "integer",
      "minimum": 1900
    },
    "title_jp": {
      "type": "string",
      "minLength": 1
    },
    "title_en": {
      "type": "string"
    },
    "title_fr": {
      "type": "string"
    },
    "rarity": {
      "type": "string",
      "enum": [
        "standard",
        "prism",
        "special"
      ]
    },
    "front_image_url": {
      "type": "string",
      "format": "uri"
    },
    "back_image_url": {
      "type": "string",
      "format": "uri"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "additionalProperties": false
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-028.json
{
  "id": "p1-028",
  "part": "1",
  "number": "028",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ホントに大丈夫か？",
  "title_en": "Are you really okay?",
  "title_fr": "Tu es sûr que ça va ?",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1-028.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1-028.png",
  "updated_at": "2025-10-25T05:19:29.049Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-059.json
{
  "id": "p2-059",
  "part": "2",
  "number": "059",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "うわわわわっ!!",
  "title_en": "Waaaah!!",
  "title_fr": "Aaaaah !!",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_2-059.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_2-059.png",
  "updated_at": "2025-09-14T14:47:04.153Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-016.json
{
  "id": "p1-016",
  "part": "1",
  "number": "016",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ブルマ",
  "title_en": "Bulma",
  "title_fr": "Bulma",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_1-016.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_1-016.png",
  "updated_at": "2025-09-14T14:47:04.134Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-072.json
{
  "id": "p2-072",
  "part": "2",
  "number": "072",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "群雄割拠!",
  "title_en": "Rival warlords vie for supremacy",
  "title_fr": "Les rivaux se disputent la suprématie !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-072.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-072.png",
  "updated_at": "2025-10-25T05:18:11.470Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-006.json
{
  "id": "p1-006",
  "part": "1",
  "number": "006",
  "year": 1991,
  "rarity": "prism",
  "title_jp": "ピッコロVSフリーザ",
  "title_en": "Piccolo VS Frieza",
  "title_fr": "Piccolo contre Freezer",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1-006.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1-006.png",
  "updated_at": "2025-10-25T05:18:11.434Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-065.json
{
  "id": "p2-065",
  "part": "2",
  "number": "065",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "許さねぇっ!!",
  "title_en": "I won’t forgive you!!",
  "title_fr": "Je ne te le pardonnerai pas !!",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_2-065.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_2-065.png",
  "updated_at": "2025-09-14T14:47:04.157Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-050.json
{
  "id": "p2-050",
  "part": "2",
  "number": "050",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "LET'S FLY!!",
  "title_en": "Let's fly!",
  "title_fr": "Envolons-nous !!",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-050.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-050.png",
  "updated_at": "2025-10-25T05:18:11.455Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-055.json
{
  "id": "p2-055",
  "part": "2",
  "number": "055",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ホールドアップ!!",
  "title_en": "Hands Up!!",
  "title_fr": "Les mains en l'air !!",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_2-055.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_2-055.png",
  "updated_at": "2025-09-14T14:47:04.152Z"
}
