=== fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/fchavonet/web-db_visual_adventure_cards_api/schema/card.schema.json",
  "title": "Visual Adventure Card",
  "type": "object",
  "required": [
    "id",
    "part",
    "number",
    "title_jp",
    "rarity",
    "front_image_url",
    "back_image_url",
    "updated_at"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^p[\\w]+-\\d{3}[a-z]?$"
    },
    "part": {
      "type": "string",
      "minLength": 1
    },
    "number": {
      "type": "string",
      "pattern": "^\\d{3}$"
    },
    "year": {
      "type": "integer",
      "minimum": 1900
    },
    "title_jp": {
      "type": "string",
      "minLength": 1
    },
    "title_en": {
      "type": "string"
    },
    "title_fr": {
      "type": "string"
    },
    "rarity": {
      "type": "string",
      "enum": [
        "standard",
        "prism",
        "special"
      ]
    },
    "front_image_url": {
      "type": "string",
      "format": "uri"
    },
    "back_image_url": {
      "type": "string",
      "format": "uri"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "additionalProperties": false
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-066.json
{
  "id": "p2-066",
  "part": "2",
  "number": "066",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "悟空大活劇!!",
  "title_en": "Goku in all-out action!!",
  "title_fr": "Goku en pleine action !!",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-066.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-066.png",
  "updated_at": "2025-10-25T05:18:11.466Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-047.json
{
  "id": "p2-047",
  "part": "2",
  "number": "047",
  "year": 1991,
  "rarity": "prism",
  "title_jp": "天下分け目の超決戦!!",
  "title_en": "The fate-deciding super showdown!!",
  "title_fr": "La grande bataille décisive !!",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-047.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-047.png",
  "updated_at": "2025-10-25T05:18:11.453Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-078.json
{
  "id": "p2-078",
  "part": "2",
  "number": "078",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ザーボンの怒り",
  "title_en": "Zarbon’s anger",
  "title_fr": "La colère de Zarbon",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-078.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-078.png",
  "updated_at": "2025-10-25T05:19:29.075Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-035.json
{
  "id": "p1-035",
  "part": "1",
  "number": "035",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "激闘開始",
  "title_en": "The fierce battle begins",
  "title_fr": "Le combat acharné commence",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_1-035.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_1-035.png",
  "updated_at": "2025-09-13T19:13:43.861Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-051.json
{
  "id": "p2-051",
  "part": "2",
  "number": "051",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "かかってこいっ!!",
  "title_en": "Bring it on!!",
  "title_fr": "Viens te battre !!",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_2-051.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_2-051.png",
  "updated_at": "2025-09-14T14:47:04.150Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-068.json
{
  "id": "p2-068",
  "part": "2",
  "number": "068",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "つかまってろよ!",
  "title_en": "Hang on!",
  "title_fr": "Accroche-toi !",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_2-068.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_2-068.png",
  "updated_at": "2025-09-14T14:47:04.158Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-071.json
{
  "id": "p2-071",
  "part": "2",
  "number": "071",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "パワーアップ!!",
  "title_en": "Power up!!",
  "title_fr": "Montée en puissance !!",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_2-071.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_2-071.png",
  "updated_at": "2025-09-14T14:47:04.159Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-053.json
{
  "id": "p2-053",
  "part": "2",
  "number": "053",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "射てーっ!!",
  "title_en": "Fire!!",
  "title_fr": "Feu !!",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_2-053.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_2-053.png",
  "updated_at": "2025-09-14T14:47:04.151Z"
}
