=== fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/fchavonet/web-db_visual_adventure_cards_api/schema/card.schema.json",
  "title": "Visual Adventure Card",
  "type": "object",
  "required": [
    "id",
    "part",
    "number",
    "title_jp",
    "rarity",
    "front_image_url",
    "back_image_url",
    "updated_at"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^p[\\w]+-\\d{3}[a-z]?$"
    },
    "part": {
      "type": "string",
      "minLength": 1
    },
    "number": {
      "type": "string",
      "pattern": "^\\d{3}$"
    },
    "year": {
      "type": "integer",
      "minimum": 1900
    },
    "title_jp": {
      "type": "string",
      "minLength": 1
    },
    "title_en": {
      "type": "string"
    },
    "title_fr": {
      "type": "string"
    },
    "rarity": {
      "type": "string",
      "enum": [
        "standard",
        "prism",
        "special"
      ]
    },
    "front_image_url": {
      "type": "string",
      "format": "uri"
    },
    "back_image_url": {
      "type": "string",
      "format": "uri"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "additionalProperties": false
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-023.json
{
  "id": "p1-023",
  "part": "1",
  "number": "023",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "第23回天下一武道会",
  "title_en": "23rd World Martial Arts Tournament",
  "title_fr": "23ᵉ Tournoi d'arts martiaux",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1-023.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1-023.png",
  "updated_at": "2025-10-25T05:19:29.048Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-048.json
{
  "id": "p2-048",
  "part": "2",
  "number": "048",
  "year": 1991,
  "rarity": "prism",
  "title_jp": "ギニュー特戦隊到着!!",
  "title_en": "The Ginyu Force arrives!!",
  "title_fr": "Le Commando Ginyu arrive !!",
  "front_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/front/part_2-048.png",
  "back_image_url": "https://fchavonet.github.io/web-db_visual_adventure_cards_api/assets/images/back/part_2-048.png",
  "updated_at": "2025-09-14T14:47:04.148Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-037.json
{
  "id": "p1-037",
  "part": "1",
  "number": "037",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "地球よ、オラに力を！",
  "title_en": "Earth, lend me your energy!",
  "title_fr": "Terre, prête-moi ton énergie !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1-037.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1-037.png",
  "updated_at": "2025-10-25T05:19:29.052Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-049.json
{
  "id": "p2-049",
  "part": "2",
  "number": "049",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "大格闘!",
  "title_en": "All-out melee!",
  "title_fr": "Combat acharné !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-049.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-049.png",
  "updated_at": "2025-10-25T05:19:29.060Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-074.json
{
  "id": "p2-074",
  "part": "2",
  "number": "074",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ついに対決の時",
  "title_en": "Finally, the time for the showdown",
  "title_fr": "Enfin, l’heure de l’affrontement",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-074.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-074.png",
  "updated_at": "2025-10-25T05:19:29.073Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-052.json
{
  "id": "p2-052",
  "part": "2",
  "number": "052",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ある夏の日",
  "title_en": "One summer day",
  "title_fr": "Un jour d’été",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-052.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-052.png",
  "updated_at": "2025-10-25T05:19:29.062Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-075.json
{
  "id": "p2-075",
  "part": "2",
  "number": "075",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "急カーブ!!",
  "title_en": "Sharp turn!!",
  "title_fr": "Virage serré !!",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-075.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-075.png",
  "updated_at": "2025-10-25T05:19:29.073Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-069.json
{
  "id": "p2-069",
  "part": "2",
  "number": "069",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "試合開始!",
  "title_en": "The match begins!",
  "title_fr": "Le combat commence !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-069.png",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-069.png",
  "updated_at": "2025-10-25T05:18:11.468Z"
}
